services:
  - type: web
    name: medimap-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_CONVEX_URL
        value: https://hidden-pelican-424.convex.cloud
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
